// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeFzJtRuyRnUcvFCuiCAc280stHfGAE4w',
    appId: '1:1087240886239:web:69c555073da493ddfc166a',
    messagingSenderId: '1087240886239',
    projectId: 'chatapp-66ae2',
    authDomain: 'chatapp-66ae2.firebaseapp.com',
    storageBucket: 'chatapp-66ae2.firebasestorage.app',
    measurementId: 'G-QYS32RX4YZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoPknZGUG684DeXdy-1fQ4ZBBM-qT8Lrk',
    appId: '1:1087240886239:android:39ea2c90d0719b5bfc166a',
    messagingSenderId: '1087240886239',
    projectId: 'chatapp-66ae2',
    storageBucket: 'chatapp-66ae2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsq8Y0uhFMgxTi2Om2NzdHah4VryEYzH8',
    appId: '1:1087240886239:ios:d81c3ece7afcdae2fc166a',
    messagingSenderId: '1087240886239',
    projectId: 'chatapp-66ae2',
    storageBucket: 'chatapp-66ae2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsq8Y0uhFMgxTi2Om2NzdHah4VryEYzH8',
    appId: '1:1087240886239:ios:d81c3ece7afcdae2fc166a',
    messagingSenderId: '1087240886239',
    projectId: 'chatapp-66ae2',
    storageBucket: 'chatapp-66ae2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeFzJtRuyRnUcvFCuiCAc280stHfGAE4w',
    appId: '1:1087240886239:web:aa17dd7eb36c6d5afc166a',
    messagingSenderId: '1087240886239',
    projectId: 'chatapp-66ae2',
    authDomain: 'chatapp-66ae2.firebaseapp.com',
    storageBucket: 'chatapp-66ae2.firebasestorage.app',
    measurementId: 'G-XS6965KHHH',
  );
}
